### ISSUE TITLE
Are you still developing?

### ISSUE THREAD

**Issue by stozk** [alexellis/scroll-phat-node#1]
Hi, 

I was wondering if you plan to finish this lib at some point...
I looked into the source and it seems like the text scroll will be tricky to implement because of node's asynchronous nature.

Do you have any ideas or have you given up on it?

BR
Daniel

**Comment by stozk** [comment]
I hacked this together to get scrolling text:

Edit: fixed timer reset.

```
var globalText = "";
var colCount = 0;
var timer;

scroll.prototype.setScrollText = function(text, delay) {

	if(timer != 'undefined') {
		clearTimeout(timer);
	};

    var that = this;

	var columnOffset=10;

	globalText = text;

	colCount = 0;

	for(var i = 0; i < globalText.length; i++) {
		var ascii = globalText.charCodeAt(i);
		var ch = that.font[ascii];
		colCount = colCount + ch.length;
    }
	colCount = colCount + globalText.length + 10;

	if(globalText !== ""){
		scrollText(that, columnOffset, 0, delay);
	}
};

function scrollText (that, columnOffset, count, delay) {  
	var origText = globalText;         
	timer = setTimeout(function () {    
		that.clearPixels();
		for(var i = 0; i < globalText.length; i++) {
			var ascii = globalText.charCodeAt(i);
			var ch = that.font[ascii];
			for(var j=0;j<ch.length;j++) {
				that.setPixels(columnOffset, ch[j], true);
				columnOffset++;
			};
			columnOffset++;
		};
		count++;
		if (origText !== globalText) {  
			clearTimeout(timer);
			return;
		};
		columnOffset = 10 - count;
		that.refresh();
		if(count > colCount) {
			count = 0;
		};
		scrollText(that, columnOffset, count, delay); 
	}, delay);
};
```

**Comment by alexellis** [comment]
Hey @stozk great to hear from you.

Using an async programming model for controlling animations is about as hard as it gets. I didn't continue with the work here for that reason.

What is making you want to use Node.js specifically?

**Comment by stozk** [comment]
I just kinda prefer Node.js... I also mostly develop in Java and Node.js.

I wanted to use this for my office door. The Pi Zero will be scanning for my BLE tag and tell people on the scroll phat if I'm nearby or not.

**Comment by alexellis** [comment]
I'd really recommend against trying to build animations with JavaScript - the timing is too hard and adds an unnecessary layer of complexity. You may like the Python library or maybe sit redis or HTTP in the middle if you need to combine Python with your existing Node code.
